pygmsh/geometry.py

By analogy with `add_physical_surface` and `add_physical_volume`, the `Physical Line` exists in Gmsh to label:
- boundaries in  two-dimensional meshes and
- subdomains in one-dimensional meshes.

added Geometry.add_physical_line instance method

---

pygmsh/geometry.py
pygmsh/helper.py

Correct name of coding is `utf-8`, with hyphen; see [PEP 263](https://www.python.org/dev/peps/pep-0263) or output of `list-coding-systems` in GNU Emacs.   Mule complains without the hyphen.

coding: utf8 -> utf-8

---

pygmsh/geometry.py

As discussed following #17, which added `add_physical_line`, here is the missing zero-dimensional analogue.
This does not include the handling of expression-lists discussed in #19.

added add_physical_point instance method to Geometry

---

doc/conf.py
doc/index.rst

Build with readthedocs theme if installed locally.
include self in toc (keyword) to populate the sidebar on RTD.
--- 
Not, we avoid to set the Theme as the readthedocs one when not on readthedocs, to avoid screwing up readthedocs that can update their theme, and thus build with the new version.

Docs fixes,

---

pygmsh/geometry.py

The current pygmsh module requires a string label to be defined when creating a new physical group. I've made the second argument in (for example) `geom.add_physical_surface(surf, label)` optional.
My reasoning for doing this:
- Mainly, labels are not required in .geo code, as can be seen in [t1.geo](https://onelab.info/svn/gmsh/trunk/tutorial/t1.geo), e.g. `Physical Point(1)`
- If a label is specified instead of an ID, gmsh internally auto-converts it to a numerical ID anyway
- I use gmsh with another software package that uses physical group IDs but ignores the labels, so being able to see the ID specifically defined in the .geo code is useful
I would have liked to use the `Physical Surface("label", id)` specification since it seems to be the most transparent notation, but it would have …

Made adding a label for physical groups optional

---

pygmsh/compound_surface.py
pygmsh/geometry.py
pygmsh/line_loop.py
pygmsh/plane_surface.py
pygmsh/ruled_surface.py
pygmsh/surface_base.py

Optionally return lateral surfaces when extruding.
This is useful for adding physical surfaces to the lateral faces that generally come up as walls in CFD simulations in extruded geometries.

Extrude lateral surfaces

---

pygmsh/helper.py

Current clean up operation `os.remove(msh_filename)` will cause a permission denied error, since msh file handle is still being hold by the system.
Removing geo file won't meet this problem because the handle has already been closed in line 96.

close msh file handle before 'remove' operation

---

pygmsh/__about__.py
pygmsh/geometry.py
pygmsh/helper.py
test/examples/__init__.py
test/examples/factory.py

The new functionality cannot be tested with the current ci since there is no gmsh-3, but it should gracefully revert to the previous behavior when using gmsh-2.
All tests are running for me with python 2.7.13 and gmsh 3.0.2

Add support for gmsh 3 factories

---

pygmsh/helper.py
test/examples/pipes.py

as reported by the wiki page mentioned in the comment, the rotation axis must be unitary, otherwise scales are not preserved.
I don't know if this was a "feature", but in that case it should be mentioned in the method description.

Assert rotation axis unitary

---

pygmsh/built_in/geometry.py

Adds the optional `make_surface` parameter to the `add_rectangle` function to allow same functionality ass `add_polygon`.

Let rectangle not be a surface

---

README.md
doc/index.rst

Fixes the documentation page. It appears to have broken when the main module was migrated to `built_in`.

Fixes the documentation page

---

pygmsh/built_in/geometry.py
test/test_layers.py

As in nschloe/pygmsh#85 (before that foundered) including SamMallinson/pygmsh#1 and SamMallinson/pygmsh#2

added layers and recombine options to extrude, & a test

---

pygmsh/built_in/geometry.py

For all cases in which `translation_axis is not None`, there is a common closure with `'};'`, just before `extrusion_string` is appended to the Gmsh code.

not prematurely closing extrusion_string if rotation_axis is None #128

---

pygmsh/built_in/geometry.py
pygmsh/built_in/spline.py
test/test_splines.py

This is intended to fulfil #135.  All of the new code, including [`test/test_splines.py`](test/test_splines.py) is nearly identical to [`test/test_bsplines.py`](test/test_bsplines.py), is nearly identical to that for BSplines, though the shapes produced by the two tests differ markedly, as they should.

Splines (not BSplines) for built_in

---

test/test_hex.py

This was motivated by queries in #83 about whether `pygmsh.built_in.Geometry.extrude` suffices for quadrilateral and hexahedral meshes.  It does.

new test_hex, constructing structured quad-hex cuboid #83

---

pygmsh/opencascade/geometry.py

Here s the first cherry pick. Separation of delete  in opencascade boolean operations methods between the input entities and the tool_entities.
Addition of a method that allows to keep the tagging of the physical geometries intact, namely volumes_inside.

separated delete's for the boolean operations. Function volume inside

---

pygmsh/built_in/line_base.py
pygmsh/built_in/line_loop.py
pygmsh/built_in/surface.py
pygmsh/built_in/surface_base.py
pygmsh/built_in/surface_loop.py
pygmsh/built_in/volume_base.py
pygmsh/opencascade/geometry.py
pygmsh/opencascade/surface_base.py
pygmsh/opencascade/volume_base.py
test/test_booleans.py

The objective is to use opencascade and builtin geometries together in boolean operations as gmsh allows it. 
The main changes are the following:
- built_in.Geometry becomes parent of opencascade.Geometry. That works very smoothly as long as the _bollean_operations is updated.
- insertion of topological dimension for each base class in built_in and opencascade by inserting a property named dimension.
- Use of that property to treat both geometry factories together within _boolean_operations
- That also replaces the use of isinstance with dimension testing in that method.
- Addition of tests using plane surfaces that test both square surface with a circular hole as well as square circle fragments. Square and circle are built using built_in geometry type, namely line_loop then PlaneSurface, …

Openc builtin

---

pygmsh/built_in/bspline.py
pygmsh/built_in/spline.py

Gmsh crashes if BSpline has only one point and throws an error if Spline does, so here insist on more.

need more than one point to make a {Bs,S}pline #150 #151

---

pygmsh/opencascade/geometry.py

the id returned from the extrude was incorrect, it needs to be based on the extrude array.  Fixes #162

Fix issue with extrusion volume id in #162

---

pygmsh/built_in/point.py

gmsh can handle optional characteristic length for Points. 
This pull request enables pygmsh to deal with it as well.

characteristic length for points is optional

---

pygmsh/built_in/geometry.py
test/test_tori.py
test/test_torus.py
test/test_torus_crowd.py

This demonstrates the exact formula for the volume of a torus #176 .  From `test_tori.py`, it drops the second torus which was constructed with `_add_torus_extrude_circle` which calls `add_compound_volume` which fails on my machine with Gmsh 3.0.7 because of the issue with compound entities #112.
I did have to increase the relative tolerance from 0.01 to 0.05.  The original tighter value can be achieved by reducing `lcar` but that makes the test take longer.

test volume of tori using exact formula

---

test/test_circle_transform.py

This addresses the issues identified in transforming circles #173:
- the transformation changed the type of the point coordinates from a two-dimensional array to a list of one-dimensional arrays
- the transformation also performed the offset, so that it was done twice if a transform was specified
It also:
- fulfils the TODO in Geometry.add_circle to assert that `R` preserves circles
- provides a new test of an offset transformed circle
The formulæ for the transformation used are taken from https://en.wikipedia.org/wiki/Rotation_matrix#General_rotations.
The test is otherwise based on `test/test_circle.py` but does not specify `compound=True` as that is currently broken #112 .

transforming circles

---

doc/index.rst

There was a typo in the underline of a heading in index.rst that prevented sphynx from compiling the docs.

Fixed typo in index.rst

---

pygmsh/built_in/geometry.py

The intention of this is to allow the provision of options when defining transfinite items, e.g.
```
geom.set_transfinite_lines([l0, l2], size=10, flag="Using Bump 0.1")
geom.set_transfinite_surface(mysurf, size=None, flag="Alternate")
```

Add optional flag to the definition of transfinite lines/surface.

---

test/test_bsplines.py

I believe it works for Gmsh < 4 and for Gmsh 4, so it should be ready for inclusion now,  unlike #214 for the Gmsh 4 compound entities.
Tested with 3.0.6 and 4.0.1-git-296dd75f0.

test bspline according to Gmsh < 4, fixes #220

---

README.md

Use the correct meshio write helper, and switch to the .vtk
format to avoid depending on the lxml module, which is not
strictly required by meshio and thus likely won't have been
installed by a beginner.
This resolves issue #234.

Fix meshio example code

---

pygmsh/built_in/geometry.py
pygmsh/built_in/point.py
pygmsh/built_in/point_base.py
pygmsh/opencascade/dummy.py
pygmsh/opencascade/geometry.py
test/test_extrusion_entities.py
test/test_opencascade_regular_extrusion.py
test/test_regular_extrusion.py

Adds the features asked for in #238 and #236, so far only for `built_in` geometries.
The `top` entity from a point extrusion is not yet usable, maybe a `PointBase` class needs to be added to get that right.
I successfully recreated my use cases with this (regular cubes and tubes), and added a simple test case in the same style.
If this goes well I will have a look at the Opencascade geometries as well, and might get around do some clean up.

[WIP] Improve extrude capabilities

---

pygmsh/__about__.py
pygmsh/built_in/geometry.py
test/test_physical.py

The only requirement to add a physical tag is to have an id, so LineBase,
SurfaceBase and VolumeBase should qualify for it.
The test case is a pretty common use case in CFD, that fails without this
patch.

relax check on suitable objects that can have a physical tag.

---

pygmsh/__about__.py
pygmsh/built_in/geometry.py
test/test_extrusion_entities.py

Polygon was not recognized as a properly "extrudable" object and it was
assigned Dummy extrusions.

improve extrusion of polygons

---

pygmsh/helpers.py

This addition allows to avoid using the meshio interface if the gmsh generated mesh suffices.

extended generate_mesh() interface to optionally keep the gmsh-generated mesh file

---

pygmsh/opencascade/ellipsoid.py
pygmsh/opencascade/geometry.py
test/test_opencascade_ellipsoid.py

This adds basic capabilities to add ellipsoids with the OpenCascade
engine. The actual implementation idea is from this mailing list post
by Christophe Geuzaine:
http://onelab.info/pipermail/gmsh/2018/011986.html
I consider this commit to be a bugfix, because with the OpenCascade
implementation inheriting from the builtin one in pygmsh, adding ellipsoids
was so far supported in the interface, but it yielded weird geometries
that were not even convex.
If you are interested, I will happily add a cutting mechanism similar
to the OC-Ball one to the Ellipsoid class.

Implement ellipsoids for the OpenCascade engine

---

pygmsh/built_in/geometry.py
test/test_rotation.py

Added missing geometry operation to built_in geometry.
Following example now works:
```
import pygmsh
import numpy as np
geom = pygmsh.built_in.Geometry()
rect = geom.add_rectangle(0.0, 2.0, 0.0, 1.0, 0.0, 0.1)
geom.rotate(rect, [0,0,0], np.pi/4, [0,0,1])
pygmsh.generate_mesh(geom, geo_filename="test_mesh.geo")
```

Added rotation to built-in geom

---

pygmsh/built_in/geometry.py
test/test_in_volume.py

This PR is in response to the request in Issue #337.
It turns out the built-in geometry already had functionality for `In Surface` so I have only added `In Volume`, using a similar style and adding docstrings for both.  
I have also changed `is_list` to False for the boolean geometry function in the OpenCascade generator.  This was necessary in order to use `In Volume/Surface` when using an object that had been modified by a boolean operation.  This change did not affect the tests, however I am not sure if there are any other unintended effects of this as I do not know what the intended functionality of `is_list` was.

Added In Volume function to force volume mesh to include point(s)/curve(s)/surface(s)

---

pygmsh/helpers.py

Fixes #354.
This works under Microsoft Windows 10 and Ubuntu 20.04.
I don't have access to a Mac, but should it also work there, it might render redundant the current hard-coded macos_gmsh_location.

shutil.which gmsh

---

pygmsh/common/geometry.py

- Changed: assert entity's dimension instead of class. This allows `set_recombined_surfaces` to be used with OCC.

Broaden scope of method set_recombined_surfaces

---

pygmsh/common/geometry.py

set_transfinite_line has the options "Progression", "Bump" and "Beta" according gmsh references.
Updated assert to enforce mesh type complies with gmsh options.

Update geometry.py with gmsh latest updates
