pygmsh/helper.py
This allows, at least the example in the readme  to work on py3.
=> Some Py3 and OS X compatibility.

pygmsh/__about__.py, pygmsh/helper.py
=> Version parse

.travis.yml, README.md, pygmsh/__about__.py, pygmsh/geometry.py, pygmsh/helper.py
=> Unicode strings in Python 2

.pylintrc, pygmsh/geometry.py, pygmsh/volume.py, pygmsh/volume_base.py, test/examples/__init__.py, test/examples/boolean.py
This one includes only the difference Boolean operator.
I'm putting it up now so that you can check if it is ok and later on I will duplicate it for intersection, union and fragments.
=> Boolean operators

test/test_layers.py
…like the rest of test/test_*.py (Sorry: VTK wasn't working here when I first proposed this test.)
=> no need for this to write msh instead of vtu

pygmsh/helpers.py, test/test_quads.py
This is for #115.  Maybe still a work-in-progress because of the Lloyd-optimization.
=> Recombine Surface for quadrilateral meshes

pygmsh/helpers.py
Simple switch to enable high order geometry meshing.
=> Add high order geometry options

pygmsh/built_in/geometry.py, test/test_rotated_layers.py
layered extrusions work also with rotation.
=> Rotated layers extrusion

test/test_booleans.py
Added a couple more boolean tests. 
Also added test for surface area of the fragments be it from geometrical elements or physical.
=> added tests for surface area computations

pygmsh/opencascade/geometry.py
Fixes #164.  Incorporates fix for #162
=> Fix multiple volumes syntax

pygmsh/__about__.py, pygmsh/built_in/geometry.py, pygmsh/opencascade/geometry.py, test/test_transfinite.py
add support for transfinite lines and surfaces with a little test.
=> Transfinite support

.circleci/config.yml, doc/conf.py, pygmsh/__about__.py, pygmsh/built_in/surface_base.py, pygmsh/helpers.py, pygmsh/opencascade/surface_base.py, pygmsh/opencascade/volume_base.py, setup.py, test/test_logo.py, test/test_opencascade_builtin_mix.py, test/test_transfinite.py, test_requirements.txt
=> Opencascade builtin mix

pygmsh/__about__.py, pygmsh/helpers.py, setup.py
=> Meshio update

pygmsh/built_in/define_constant.py, test/test_define_constant.py
Adds test based on Rectangle test, but with the fixed values replaced with `DefineConstant`s.
=> Adds test for define constant.

pygmsh/built_in/geometry.py, test/test_booleans.py
=> fix for polygon booleans

pygmsh/built_in/geometry.py
=> LineBase covers Line & CircleArc, & missing EllipseArc

.circleci/config.yml, .github/workflows/ci.yml, Makefile, codecov.yml
=> Create gh release

pygmsh/built_in/geometry.py, test/test_recombine.py
Adding function and corresponding test. It seems to work find but I eagerly await your feedback.
=> Adding function to recombine mesh for generation of quad elements

MANIFEST.in, pygmsh/__about__.py
Fixes https://github.com/nschloe/pygmsh/issues/310.
=> add MANIFEST.in

pygmsh/common/dummy.py, pygmsh/common/geometry.py, pygmsh/common/line.py, pygmsh/common/plane_surface.py, pygmsh/common/point.py, pygmsh/common/polygon.py, pygmsh/occ/ball.py, pygmsh/occ/boolean.py, pygmsh/occ/box.py, pygmsh/occ/cylinder.py, pygmsh/occ/disk.py, pygmsh/occ/dummy.py, pygmsh/occ/geometry.py, pygmsh/occ/rectangle.py, setup.cfg, test/built_in/test_airfoil.py, test/built_in/test_ball_with_stick.py, test/built_in/test_circle.py, test/built_in/test_embed.py, test/built_in/test_hex.py, test/built_in/test_pacman.py, test/built_in/test_unordered_unoriented.py
=> Physical groups

pygmsh/common/geometry.py, pygmsh/geo/geometry.py, setup.cfg
=> fix for physical entities

pygmsh/common/geometry.py, pygmsh/geo/dummy.py, pygmsh/geo/geometry.py, pygmsh/occ/geometry.py, setup.cfg, tox.ini
=> be less strict on occ::revolve()

pygmsh/occ/torus.py, setup.cfg, test/built_in/test_embed.py
=> Torus dimtag

pygmsh/common/bspline.py, pygmsh/common/circle_arc.py, pygmsh/common/curve_loop.py, pygmsh/common/dummy.py, pygmsh/common/ellipse_arc.py, pygmsh/common/geometry.py, pygmsh/common/line.py, pygmsh/common/line_base.py, pygmsh/common/plane_surface.py, pygmsh/common/point.py, pygmsh/common/polygon.py, pygmsh/common/spline.py, pygmsh/common/surface.py, pygmsh/common/surface_loop.py, pygmsh/common/volume.py, pygmsh/geo/dummy.py, pygmsh/geo/geometry.py, pygmsh/helpers.py, pygmsh/occ/ball.py, pygmsh/occ/box.py, pygmsh/occ/cone.py, pygmsh/occ/cylinder.py, pygmsh/occ/disk.py, pygmsh/occ/dummy.py, pygmsh/occ/rectangle.py, pygmsh/occ/torus.py, pygmsh/occ/wedge.py, setup.cfg
=> More dimtags

pygmsh/occ/ball.py, pygmsh/occ/cylinder.py, pygmsh/occ/torus.py, pygmsh/occ/wedge.py
- Fixed: missing `dim` attribute for several entities.
=> Add missing dim attribute

pygmsh/common/geometry.py, test/test_labels.py
=> disallow duplicate labels

README.md, pygmsh/__init__.py, pygmsh/helpers.py, pygmsh/occ/geometry.py, setup.cfg, test/occ/test_opencascade_booleans.py
=> Boolean vs SIZE_QUEUE

pygmsh/common/geometry.py
=> more type hints

pygmsh/occ/geometry.py, setup.cfg
=> add import_shapes()

pygmsh/common/geometry.py, pygmsh/geo/geometry.py, pygmsh/occ/geometry.py
My attempt to fix up the mess of my previous pull request. Fixes #434.
Replaces the hot mess that is #435.
The names have been changed and default values added inline with @nschloe 's comment [here](https://github.com/nschloe/pygmsh/issues/435#issuecomment-792361504_)
=> Adds optional arguments to gmsh init

src/pygmsh/common/bezier.py, src/pygmsh/common/geometry.py
Added a function similar to bsplines for adding Bézier curve
=> Add bezier func
